name: dhf
channels:
  - pytorch
  - plotly
  - defaults
dependencies:
  - pip
  - pillow=9.4.0
  - python=3.8
  - pytorch=1.10.2
  - scipy=1.7.3
  - torchvision=0.11.3
  - ffmpeg=4.2.2
  - pip:
    - numpy==1.22.4
    - opencv-python==4.7.0.72
    - pandas==1.5.3
    - tqdm==4.65.0
    - wget==3.2
    - scikit-learn==1.0.2
    - fvcore==0.1.5.post20221221
    - imageio==2.4.1
    - diffusers==0.14.0
    - transformers==4.27.4
    - wandb==0.14.2
    - omegaconf==2.3.0
    - ipympl==0.9.3
    - einops==0.6.1
    - mediapy==1.1.8